### PR TITLE
lein2deps: add javac prep lib support

### LINKED ISSUE #4: lein2deps: add support for Java compilation?
Leiningen supports compiling Java sources out of the box (via `:java-source-paths`). Supporting this to some degree would be desirable because it unlocks using libraries relying on this to be used as git dependencies. This requires generating a `:deps/prep-lib` task. In Aleph, [we already have this](https://github.com/clj-commons/aleph/blob/master/deps/aleph/lein_to_deps.clj#L43-L53). It also [generates a `build.edn`](https://github.com/clj-commons/aleph/blob/master/deps/aleph/lein_to_deps.clj#L54-L57) file from the relevant Leiningen settings which is then consumed by a generic [build namespace](https://github.com/clj-commons/aleph/blob/master/deps/aleph/build.clj). Do you think including something like this in `lein2deps` is worthwhile? 

Some background on the workflow in Aleph: The idea is to keep Leiningen around as the leading build tool (at least for now or maybe even indefinitely) and generate a `deps.edn` whenever we change `project.clj` which provides just enough to be able to use Aleph as a git dependency. We'd be happy to switch over to `lein2deps` so that we can share the maintenance burden for this.

### PR DESCRIPTION
**Pull request by DerGuteMoritz**
Fixes #4.

### CODE REVIEW

**Comment by borkdude** [comment]
Fantastic :)

**Comment by borkdude** [comment]
Btw, I don't think `:compile-path` is mandatory in `project.clj` for Java compilation to happen

**Comment by DerGuteMoritz** [comment]
> Btw, I don't think `:compile-path` is mandatory in `project.clj` for Java compilation to happen

That's correct but without adding it to `:paths` in `deps.edn`, the class files would not be picked up by `tools.deps`. And as discussed in https://github.com/borkdude/tools/pull/3, we're currently not filling in the default `:compile-path` when it's not set. I guess we should either document that it's required to explicitly specify both `:java-source-paths` *and* `:compile-path` for using this feature or we could fill in the default `:compile-path` of `target/classes` if *only* `:java-source-paths`  is given. WDYT?

**Comment by borkdude** [comment]
I think filling in the default `:compile-path` would make lein2deps less surprising?

**Pull request merged**
